---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2026/7/13 11:22
---
if(redis.call('get',KEY[1]) == ARGV[1])then
    return redis.call('del',KEYS[1])
end
return 0