---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2026/7/15 10:48
---

---秒杀券id
local voucherId = ARGV[1]

---用户id
local userId = ARGV[2]

---库存key
local stockkey = "seckill:stock:" .. voucherId

---订单key
local orderkey = "seckill:order" .. voucherId

---判断库存是否充足
if(tonumber(redis.call('get',stockkey))<=0)then
    return 1
end

---判断是否重复下单
if(redis.call('sismember',orderkey,userId) == 1)then
    return 2
end

---满足条件，库存减一
redis.call('incrby',stockkey,-1)
---满足条件，保存用户id
redis.call('sadd',orderkey,userId)

return 0